-- ========================================
-- 书道心电图 - 卡片信息多端同步
-- 版本: v1.05.0
-- 功能: 用户编辑的卡片信息云端同步
-- ========================================

-- ========================================
-- 1. 卡片设置表 (calligraphy_card_settings)
-- ========================================

CREATE TABLE IF NOT EXISTS public.calligraphy_card_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    card_id INTEGER NOT NULL,
    icon TEXT NOT NULL DEFAULT '🖌️',
    name TEXT NOT NULL,
    age TEXT NOT NULL,
    style_title TEXT NOT NULL,
    style_desc TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- 确保每个用户对每张卡片只有一条设置记录
    CONSTRAINT calligraphy_card_settings_unique UNIQUE (user_id, card_id),

    -- 字段长度限制
    CONSTRAINT calligraphy_card_settings_icon_length CHECK (CHAR_LENGTH(icon) <= 2),
    CONSTRAINT calligraphy_card_settings_name_not_empty CHECK (CHAR_LENGTH(TRIM(name)) > 0),
    CONSTRAINT calligraphy_card_settings_age_not_empty CHECK (CHAR_LENGTH(TRIM(age)) > 0),
    CONSTRAINT calligraphy_card_settings_style_title_not_empty CHECK (CHAR_LENGTH(TRIM(style_title)) > 0),
    CONSTRAINT calligraphy_card_settings_style_desc_not_empty CHECK (CHAR_LENGTH(TRIM(style_desc)) > 0)
);

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_calligraphy_card_settings_user_id ON public.calligraphy_card_settings(user_id);
CREATE INDEX IF NOT EXISTS idx_calligraphy_card_settings_card_id ON public.calligraphy_card_settings(card_id);
CREATE INDEX IF NOT EXISTS idx_calligraphy_card_settings_updated_at ON public.calligraphy_card_settings(updated_at DESC);

-- 添加注释
COMMENT ON TABLE public.calligraphy_card_settings IS '用户自定义卡片设置表（多端同步）';
COMMENT ON COLUMN public.calligraphy_card_settings.user_id IS '用户ID';
COMMENT ON COLUMN public.calligraphy_card_settings.card_id IS '卡片ID（1-6对应书法家）';
COMMENT ON COLUMN public.calligraphy_card_settings.icon IS '书法家图标（emoji）';
COMMENT ON COLUMN public.calligraphy_card_settings.name IS '书法家姓名';
COMMENT ON COLUMN public.calligraphy_card_settings.age IS '生卒年份及朝代';
COMMENT ON COLUMN public.calligraphy_card_settings.style_title IS '风格标题';
COMMENT ON COLUMN public.calligraphy_card_settings.style_desc IS '风格描述';
COMMENT ON COLUMN public.calligraphy_card_settings.updated_at IS '最后更新时间';

-- ========================================
-- 2. 启用 RLS (Row Level Security)
-- ========================================

ALTER TABLE public.calligraphy_card_settings ENABLE ROW LEVEL SECURITY;

-- ========================================
-- 3. RLS 策略
-- ========================================

-- 先删除已存在的策略（如果存在）
DROP POLICY IF EXISTS "Users can view own card settings" ON public.calligraphy_card_settings;
DROP POLICY IF EXISTS "Users can insert own card settings" ON public.calligraphy_card_settings;
DROP POLICY IF EXISTS "Users can update own card settings" ON public.calligraphy_card_settings;
DROP POLICY IF EXISTS "Users can delete own card settings" ON public.calligraphy_card_settings;

-- 用户只能查看自己的设置
CREATE POLICY "Users can view own card settings"
ON public.calligraphy_card_settings FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- 用户可以插入自己的设置
CREATE POLICY "Users can insert own card settings"
ON public.calligraphy_card_settings FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- 用户可以更新自己的设置
CREATE POLICY "Users can update own card settings"
ON public.calligraphy_card_settings FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 用户可以删除自己的设置
CREATE POLICY "Users can delete own card settings"
ON public.calligraphy_card_settings FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- ========================================
-- 4. 自动更新 updated_at 触发器
-- ========================================

-- 先删除已存在的触发器（如果存在）
DROP TRIGGER IF EXISTS update_calligraphy_card_settings_updated_at ON public.calligraphy_card_settings;

-- 添加触发器
CREATE TRIGGER update_calligraphy_card_settings_updated_at
    BEFORE UPDATE ON public.calligraphy_card_settings
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- ========================================
-- 5. 便捷的Upsert函数
-- ========================================

-- 创建或替换upsert函数：如果存在则更新，不存在则插入
CREATE OR REPLACE FUNCTION public.upsert_card_settings(
    p_user_id UUID,
    p_card_id INTEGER,
    p_icon TEXT,
    p_name TEXT,
    p_age TEXT,
    p_style_title TEXT,
    p_style_desc TEXT
) RETURNS JSON AS $$
DECLARE
    result JSON;
BEGIN
    INSERT INTO public.calligraphy_card_settings (
        user_id, card_id, icon, name, age, style_title, style_desc
    ) VALUES (
        p_user_id, p_card_id, p_icon, p_name, p_age, p_style_title, p_style_desc
    )
    ON CONFLICT (user_id, card_id)
    DO UPDATE SET
        icon = EXCLUDED.icon,
        name = EXCLUDED.name,
        age = EXCLUDED.age,
        style_title = EXCLUDED.style_title,
        style_desc = EXCLUDED.style_desc,
        updated_at = NOW()
    RETURNING row_to_json(*) INTO result;

    RETURN result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ========================================
-- 6. 验证安装
-- ========================================

-- 检查表是否创建成功
SELECT
    tablename,
    schemaname
FROM pg_tables
WHERE tablename = 'calligraphy_card_settings'
AND schemaname = 'public';

-- 检查策略是否创建成功
SELECT
    tablename,
    policyname,
    cmd,
    roles
FROM pg_policies
WHERE tablename = 'calligraphy_card_settings'
AND schemaname = 'public';
