-- ========================================
-- 书道心电图 - 社区功能数据库设计
-- 版本: v1.04.0
-- 功能: 点赞和评论功能
-- ========================================

-- ========================================
-- 1. 点赞表 (calligraphy_likes)
-- ========================================

CREATE TABLE IF NOT EXISTS public.calligraphy_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    card_id INTEGER NOT NULL,
    image_path TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- 确保用户对同一图片只能点赞一次
    CONSTRAINT calligraphy_likes_unique UNIQUE (user_id, image_path)
);

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_calligraphy_likes_user_id ON public.calligraphy_likes(user_id);
CREATE INDEX IF NOT EXISTS idx_calligraphy_likes_card_id ON public.calligraphy_likes(card_id);
CREATE INDEX IF NOT EXISTS idx_calligraphy_likes_image_path ON public.calligraphy_likes(image_path);

-- 添加注释
COMMENT ON TABLE public.calligraphy_likes IS '书法作品点赞表';
COMMENT ON COLUMN public.calligraphy_likes.user_id IS '点赞用户的ID';
COMMENT ON COLUMN public.calligraphy_likes.card_id IS '卡片ID（1-6对应书法家）';
COMMENT ON COLUMN public.calligraphy_likes.image_path IS '图片在Storage中的路径';
COMMENT ON COLUMN public.calligraphy_likes.created_at IS '点赞时间';

-- ========================================
-- 2. 评论表 (calligraphy_comments)
-- ========================================

-- 创建表（如果不存在）
CREATE TABLE IF NOT EXISTS public.calligraphy_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    card_id INTEGER NOT NULL,
    image_path TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- 评论长度限制
    CONSTRAINT calligraphy_comments_content_length CHECK (CHAR_LENGTH(content) > 0 AND CHAR_LENGTH(content) <= 500)
);

-- 添加缺失的列（如果不存在）
DO $$
BEGIN
    -- 添加 user_name 列
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'calligraphy_comments' AND column_name = 'user_name'
    ) THEN
        ALTER TABLE public.calligraphy_comments ADD COLUMN user_name TEXT NOT NULL DEFAULT '匿名用户';
    END IF;

    -- 添加 user_email 列
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'calligraphy_comments' AND column_name = 'user_email'
    ) THEN
        ALTER TABLE public.calligraphy_comments ADD COLUMN user_email TEXT NOT NULL DEFAULT '';
    END IF;
END $$;

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_calligraphy_comments_user_id ON public.calligraphy_comments(user_id);
CREATE INDEX IF NOT EXISTS idx_calligraphy_comments_card_id ON public.calligraphy_comments(card_id);
CREATE INDEX IF NOT EXISTS idx_calligraphy_comments_image_path ON public.calligraphy_comments(image_path);
CREATE INDEX IF NOT EXISTS idx_calligraphy_comments_created_at ON public.calligraphy_comments(created_at DESC);

-- 添加注释
COMMENT ON TABLE public.calligraphy_comments IS '书法作品评论表';
COMMENT ON COLUMN public.calligraphy_comments.user_id IS '评论用户的ID';
COMMENT ON COLUMN public.calligraphy_comments.user_name IS '评论用户名称（冗余存储，便于查询）';
COMMENT ON COLUMN public.calligraphy_comments.user_email IS '评论用户邮箱（冗余存储，便于显示）';
COMMENT ON COLUMN public.calligraphy_comments.card_id IS '卡片ID（1-6对应书法家）';
COMMENT ON COLUMN public.calligraphy_comments.image_path IS '图片在Storage中的路径';
COMMENT ON COLUMN public.calligraphy_comments.content IS '评论内容（最多500字）';
COMMENT ON COLUMN public.calligraphy_comments.created_at IS '评论时间';
COMMENT ON COLUMN public.calligraphy_comments.updated_at IS '更新时间';

-- ========================================
-- 3. 启用 RLS (Row Level Security)
-- ========================================

ALTER TABLE public.calligraphy_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calligraphy_comments ENABLE ROW LEVEL SECURITY;

-- ========================================
-- 4. 点赞表 RLS 策略
-- ========================================

-- 先删除已存在的策略（如果存在）
DROP POLICY IF EXISTS "Anyone can view likes" ON public.calligraphy_likes;
DROP POLICY IF EXISTS "Authenticated users can insert likes" ON public.calligraphy_likes;
DROP POLICY IF EXISTS "Users can delete own likes" ON public.calligraphy_likes;

-- 所有用户（包括未登录）都可以查看点赞
CREATE POLICY "Anyone can view likes"
ON public.calligraphy_likes FOR SELECT
TO authenticated, anon
USING (true);

-- 登录用户可以点赞
CREATE POLICY "Authenticated users can insert likes"
ON public.calligraphy_likes FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- 用户只能删除自己的点赞
CREATE POLICY "Users can delete own likes"
ON public.calligraphy_likes FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- ========================================
-- 5. 评论表 RLS 策略
-- ========================================

-- 先删除已存在的策略（如果存在）
DROP POLICY IF EXISTS "Anyone can view comments" ON public.calligraphy_comments;
DROP POLICY IF EXISTS "Authenticated users can insert comments" ON public.calligraphy_comments;
DROP POLICY IF EXISTS "Users can update own comments" ON public.calligraphy_comments;
DROP POLICY IF EXISTS "Users can delete own comments" ON public.calligraphy_comments;

-- 所有用户（包括未登录）都可以查看评论
CREATE POLICY "Anyone can view comments"
ON public.calligraphy_comments FOR SELECT
TO authenticated, anon
USING (true);

-- 登录用户可以发表评论
CREATE POLICY "Authenticated users can insert comments"
ON public.calligraphy_comments FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- 用户只能更新自己的评论
CREATE POLICY "Users can update own comments"
ON public.calligraphy_comments FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 用户只能删除自己的评论
CREATE POLICY "Users can delete own comments"
ON public.calligraphy_comments FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- ========================================
-- 6. 自动更新 updated_at 触发器
-- ========================================

-- 为评论表创建更新时间戳函数
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 先删除已存在的触发器（如果存在）
DROP TRIGGER IF EXISTS update_calligraphy_comments_updated_at ON public.calligraphy_comments;

-- 添加触发器
CREATE TRIGGER update_calligraphy_comments_updated_at
    BEFORE UPDATE ON public.calligraphy_comments
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- ========================================
-- 7. 有用的视图和辅助函数
-- ========================================

-- 先删除已存在的视图（如果存在）
DROP VIEW IF EXISTS public.calligraphy_engagement;

-- 创建视图：获取每个图片的点赞数和评论数
CREATE OR REPLACE VIEW public.calligraphy_engagement AS
SELECT
    cl.card_id,
    cl.image_path,
    COUNT(DISTINCT cl.user_id) AS like_count,
    COUNT(DISTINCT cc.id) AS comment_count
FROM public.calligraphy_likes cl
FULL OUTER JOIN public.calligraphy_comments cc ON cl.card_id = cc.card_id AND cl.image_path = cc.image_path
GROUP BY cl.card_id, cl.image_path;

COMMENT ON VIEW public.calligraphy_engagement IS '每个图片的互动统计（点赞数和评论数）';

-- ========================================
-- 8. 验证安装
-- ========================================

-- 检查表是否创建成功
SELECT
    tablename,
    schemaname
FROM pg_tables
WHERE tablename IN ('calligraphy_likes', 'calligraphy_comments')
AND schemaname = 'public';

-- 检查策略是否创建成功
SELECT
    tablename,
    policyname,
    cmd,
    roles
FROM pg_policies
WHERE tablename IN ('calligraphy_likes', 'calligraphy_comments')
AND schemaname = 'public';
